- framework/vendor/abstracts/AbstractBotCommand.java
- framework/vendor/utilities/formatting/DiscordFormatter.java
- src/app/BotCommandsLinker.java
- src/utilities/interfaces/Commands.java
> Add Discord text formatting utilities to the Framework

- framework/vendor/utilities/settings/Setting.java
- framework/vendor/utilities/settings/SettingField.java
- src/app/CommandRouter.java
- src/commands/CommandSetting.java
- src/commands/CommandStop.java
- src/utilities/BotCommand.java
- src/utilities/interfaces/Resources.java
> Add confirm_stop setting for StopCommand

- framework/vendor/utilities/settings/TextRegexField.java
> Add TextRegexField setting type

- framework/vendor/abstracts/CommandsLinker.java
- src/commands/CommandHelp.java
> Invert behavior of help command to not show commands desc. by default

- src/commands/CommandMusicVolume.java
- src/commands/CommandSetting.java
- src/utilities/interfaces/Resources.java
- src/utilities/music/MusicPlayer.java
> Add volume setting

- framework/vendor/abstracts/AbstractBotCommand.java
- framework/vendor/interfaces/DiscordUtils.java
- framework/vendor/objects/Mention.java
Do not merge in yet
Closes #61
> [WIP] Add Mention object and methods to get the contents as a Mention object

- src/commands/CommandSpam.java
The commandSpam method has been optimized to now use the latest framework usage, such as the parameters and the new onParameterPresent method.
Closes #16
> Add user parameter feature to CommandSpam

- pom.xml
- res/lang/strings_en_US.properties
- res/lang/strings_fr_CA.properties
- src/commands/CommandMusicPlay.java
- src/utilities/music/MusicManager.java
For the time being only the first result
> Allow to search youtube with key words

- res/lang/strings_en_US.properties
- res/lang/strings_fr_CA.properties
- src/commands/CommandMusicPlay.java
- src/commands/CommandMusicReplay.java
- src/commands/CommandReplay.java
- src/utilities/abstracts/MusicCommands.java
- src/utilities/interfaces/Commands.java
- src/utilities/music/AudioListener.java
> Add replay command

- src/commands/CommandMusicPlay.java
- Few other tweaks such as not connecting to a voicechannel if an error occur
- Few formattings (or removal of unused initialization)
Ref #14
> Tweak play command to not search youtube if no env var is set

- res/lang/strings_en_US.properties
- res/lang/strings_fr_CA.properties
- src/commands/CommandMusicPlay.java
> Add the ability to play a random playlist 

- framework/vendor/Framework.java
- framework/vendor/abstracts/ModuleOutputtable.java
- framework/vendor/interfaces/Auditable.java
- framework/vendor/interfaces/Loggable.java
- framework/vendor/interfaces/Outputtable.java
- framework/vendor/modules/Audit.java
- framework/vendor/modules/Environment.java
- framework/vendor/modules/Logger.java
- framework/vendor/objects/AuditableFile.java
- framework/vendor/objects/Request.java
- src/app/CommandRouter.java
- src/app/Main.java
Refer to following issues for feedback :
Closes #63
Closes #64
Closes #65
> [WIP] Add Audit module and usage

- framework/vendor/utilities/sanitizers/BooleanSanitizer.java
- framework/vendor/utilities/sanitizers/CharSanitizer.java
- framework/vendor/utilities/sanitizers/EnumSanitizer.java
- framework/vendor/utilities/sanitizers/IntegerSanitizer.java
- framework/vendor/utilities/sanitizers/TextLengthSanitizer.java
- framework/vendor/utilities/sanitizers/TextNotEmptySanitizer.java
- framework/vendor/utilities/sanitizers/TextRegexSanitizer.java
- framework/vendor/utilities/sanitizers/TextSanitizer.java
- framework/vendor/utilities/settings/BooleanField.java
- framework/vendor/utilities/settings/CharField.java
- framework/vendor/utilities/settings/EnumField.java
- framework/vendor/utilities/settings/IntegerField.java
- framework/vendor/utilities/settings/TextField.java
- framework/vendor/utilities/settings/TextLengthField.java
- framework/vendor/utilities/settings/TextNotEmptyField.java
- framework/vendor/utilities/settings/TextRegexField.java
> Add Sanitizers utilities

- src/commands/CommandClear.java
This allows for far better condition management for clearing messages.
Also, the batchDelete messages action will take consideration the condition supplied to the method, so it'll be much more efficient.
Closes #132
> Refactor CommandClear to allow for easier condition management

- src/utilities/interfaces/Resources.java
Changing the prefix closes #138
> Change prefix from "!!" to "\"

- src/commands/CommandClear.java
> Fix bug with clear for user not clearing

- src/commands/CommandClear.java
> add the ability to notify of the clear action

- src/commands/CommandClear.java
> Add invert parameter to CommandClear

- framework/vendor/objects/Request.java
> Optimize Request constructor

- src/commands/CommandSpam.java
> Fix Spam not stopping when using the stop command (#174)

- framework/vendor/utilities/sanitizers/EnumSanitizer.java
- src/commands/CommandMusicPlay.java
> Add handling of an environment variable that changes the list of \play --random

- src/main/java/io/github/vhoyon/bot/commands/CommandMusicPlay.java
This pr is to fix the bug with the youtube search. closes #191
> Fixes the youtube search when to only find videos

- src/main/java/io/github/vhoyon/bot/commands/CommandMusicPlay.java
- src/main/java/io/github/vhoyon/bot/utilities/music/MusicManager.java
> A confirmation when a user tries to add a random playlist to the queue

- src/main/java/io/github/vhoyon/bot/commands/CommandMusicPlay.java
> A check to see if the bot is already playing in an other voicechannel

- src/main/java/io/github/vhoyon/bot/commands/CommandClear.java
> Add force parameter to CommandClear

- src/main/java/io/github/vhoyon/bot/commands/CommandClear.java
- src/main/resources/lang/strings_en_US.properties
> Add's the clearing of the commands that start with a prefix

- src/main/java/io/github/vhoyon/bot/utilities/music/AudioListener.java
> Adds a check when the bot disconnects due to inactivity to decide to send a message or not
